import { Gender, Profile } from './types';

export const INITIAL_FILTERS = {
  gender: Gender.Any,
  ageRange: [18, 50] as [number, number],
  maxDistance: 50,
};

export const PORTRAIT_PROFILES: Profile[] = [
  {
    id: 'p1',
    name: 'Sarah (Network)',
    age: 24,
    gender: Gender.Female,
    distance: 2,
    imageUrl: 'https://picsum.photos/400/400?random=101',
    bio: 'Looking for photography collaborations.',
    isEstablished: true,
  },
  {
    id: 'p2',
    name: 'James (Work)',
    age: 29,
    gender: Gender.Male,
    distance: 12,
    imageUrl: 'https://picsum.photos/400/400?random=102',
    bio: 'Tech lead seeking developers.',
    isEstablished: true,
  },
  {
    id: 'p3',
    name: 'Alex',
    age: 22,
    gender: Gender.NonBinary,
    distance: 5,
    imageUrl: 'https://picsum.photos/400/400?random=103',
    bio: 'Art student looking for mentorship.',
    isEstablished: false,
  },
  {
    id: 'p4',
    name: 'Emily',
    age: 27,
    gender: Gender.Female,
    distance: 35,
    imageUrl: 'https://picsum.photos/400/400?random=104',
    bio: 'Yoga instructor, expanding classes.',
    isEstablished: false,
  },
  {
    id: 'p5',
    name: 'Michael',
    age: 32,
    gender: Gender.Male,
    distance: 8,
    imageUrl: 'https://picsum.photos/400/400?random=105',
    bio: 'Chef seeking sous chef.',
    isEstablished: false,
  },
];

export const LANDSCAPE_PROFILES: Profile[] = [
  {
    id: 'l1',
    name: 'Jessica (Date)',
    age: 21,
    gender: Gender.Female,
    distance: 45,
    imageUrl: 'https://picsum.photos/400/400?random=201',
    bio: 'Surfer girl looking for beach vibes 🌊',
    isEstablished: true,
  },
  {
    id: 'l2',
    name: 'David (Match)',
    age: 40,
    gender: Gender.Male,
    distance: 3,
    imageUrl: 'https://picsum.photos/400/400?random=202',
    bio: 'Jazz lover looking for a concert buddy 🎷',
    isEstablished: true,
  },
  {
    id: 'l3',
    name: 'Sophie',
    age: 26,
    gender: Gender.Female,
    distance: 15,
    imageUrl: 'https://picsum.photos/400/400?random=203',
    bio: 'Digital nomad, show me your city! ✈️',
    isEstablished: false,
  },
  {
    id: 'l4',
    name: 'Ryan',
    age: 28,
    gender: Gender.Male,
    distance: 10,
    imageUrl: 'https://picsum.photos/400/400?random=204',
    bio: 'Gym rat and protein shake connoisseur 💪',
    isEstablished: false,
  },
  {
    id: 'l5',
    name: 'Emma',
    age: 25,
    gender: Gender.Female,
    distance: 20,
    imageUrl: 'https://picsum.photos/400/400?random=205',
    bio: 'Dog mom 🐶 Let\'s go for a walk.',
    isEstablished: false,
  },
  {
    id: 'l6',
    name: 'Marcus',
    age: 30,
    gender: Gender.Male,
    distance: 5,
    imageUrl: 'https://picsum.photos/400/400?random=206',
    bio: 'Coffee date? ☕️',
    isEstablished: false,
  }
];